# Generated by Django 5.2.5 on 2025-09-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipovani', '0002_match_correct_answer_match_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='question',
            field=models.CharField(default='Nová otázka?', max_length=200),
        ),
        migrations.AlterField(
            model_name='matchtip',
            name='question_answer',
            field=models.BooleanField(default=False),
        ),
    ]
