# Generated by Django 5.2.5 on 2025-09-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipovani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='correct_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='question',
            field=models.CharField(default='Nová otázka?', max_length=200),
        ),
        migrations.AddField(
            model_name='matchtip',
            name='question_answer',
            field=models.BooleanField(default=False),
        ),
    ]
