# Generated by Django 5.2.5 on 2025-09-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipovani', '0002_match_correct_answer_match_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchtip',
            name='question_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='correct_answer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='matchtip',
            name='question_answer',
            field=models.BooleanField(null=True),
        ),
    ]
