# Generated by Django 5.2.5 on 2025-09-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipovani', '0003_matchtip_question_point_alter_match_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='correct_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
